preprocessing: 
  vol_data_path: "../data/raw/inbound_volume_data.csv"
  prod_data_path: "../data/raw/production_data.csv"
  covid_data_path: "../data/raw/Covid-19_cases_age_specific.csv"

  vol_silver_path: "../data/silver/historical_volume_silver.parquet"
  prod_silver_path: "../data/silver/production_plannig_silver.parquet"
  covid_silver_path: "../data/silver/monthly_covid_rate_per_country.parquet"

  vol_gold_path: "../data/gold/historical_volume_gold.parquet"
  prod_gold_path: "../data/gold/production_plannig_gold.parquet"
  covid_gold_path: "../data/gold/monthly_covid_rate_per_country_gold.parquet"



data_quality:
  ts_len_threshold: 8

