preprocessing: 

  # Bronze Tables
  vol_data_path: "../data/raw/inbound_volume_data.csv"
  prod_data_path: "../data/raw/production_data.csv"
  covid_data_path: "../data/raw/Covid-19_cases_age_specific.csv"

  # Silver Tables
  vol_silver_path: "../data/silver/historical_volume_silver.parquet"
  prod_silver_path: "../data/silver/production_plannig_silver.parquet"
  covid_silver_path: "../data/silver/monthly_covid_rate_per_country.parquet"

  # Gold tables
  vol_gold_path: "../data/gold/historical_volume_gold.parquet"
  prod_gold_path: "../data/gold/production_plannig_gold.parquet"
  covid_gold_path: "../data/gold/monthly_covid_rate_per_country_gold.parquet"
  ratio_gold_path: "../data/gold/ratio_vol_prod_gold.parquet"
  seasonal_feat_gold_path: "../data/gold/seasonal_feat_gold.parquet"
  timeseries_gold_path: "../data/gold/timeseries_gold.parquet"

  # Reports
  pdf_report_ratios_path: "../reports/Timeseries_Vol_Prod_Ratio.pdf"

data_quality:
  ts_len_threshold: 8

feature_eng:
  lag_months: [2 ,3, 4, 5, 6]
  rolling_months: [2, 4, 6]
  drop_cols : ['Actual_Vol_[Tons]', 
             'Expected_Vol_[Tons]',
             'Vol/Prod_ratio_ton',
             'Actual_Vol_[Kg]']
  target_col: "Vol/Prod_ratio_kg"
  expected_vol_col: "Expected_Vol_[Kg]"
  expected_vol_col_rename: "expected_vol_kg"
  seasonal_features: 
    trend:
      apply: True
      col_name: "trend"
      rolling_months: [2, 4, 6]
      lag_months: [2 ,3, 4, 5, 6]
    sesonality:
      apply: True
      col_name: "sesonality"
      rolling_months: [6, 12]
      lag_months: [6, 12]
    residuals: 
      apply: True
      col_name: "residuals"
      rolling_months: [2, 4, 6]
      lag_months: [2 ,3, 4, 5, 6]
  covid_features:
    apply: True
    cols_names: ['Austria', 'Belgium', 'Croatia', 'Cyprus', 'Czechia',
       'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece',
       'Hungary', 'Iceland', 'Ireland', 'Italy', 'Latvia', 'Liechtenstein',
       'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Norway', 'Poland',
       'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden']
    rolling_months: [4, 6, 12]
    lag_months: [4, 6, 12]
  production_features: 
    apply: False
    production:
      col_name: 'Production'
      rolling_months: [4, 6, 12]
      lag_months: [4, 6, 12]

